//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class risTabulky : DbContext
    {
        public risTabulky()
            : base("name=risTabulky")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<addition> addition { get; set; }
        public DbSet<alergen> alergen { get; set; }
        public DbSet<food> food { get; set; }
        public DbSet<food_additions> food_additions { get; set; }
        public DbSet<food_alergens> food_alergens { get; set; }
        public DbSet<food_order> food_order { get; set; }
        public DbSet<food_rating> food_rating { get; set; }
        public DbSet<food_ratings> food_ratings { get; set; }
        public DbSet<food_type> food_type { get; set; }
        public DbSet<order_foods> order_foods { get; set; }
        public DbSet<ris_user> ris_user { get; set; }
        public DbSet<dining_table> dining_table { get; set; }
        public DbSet<table_reservations> table_reservations { get; set; }
        public DbSet<user_orders> user_orders { get; set; }
    }
}
